export const SOURCING_CONFIG = Symbol("SOURCING_CONFIG");
export const SOURCING_PLAN_GENERATOR = Symbol("SOURCING_PLAN_GENERATOR");
export const SOURCING_SUPPLIER_SEARCH = Symbol("SOURCING_SUPPLIER_SEARCH");
export const SOURCING_BUYER_FACTORY = Symbol("SOURCING_BUYER_FACTORY");
