[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
cache_path = "cache"
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
libs = ["node_modules", "lib"]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
